title: Fragify - CS2 Stats Visualizing System
description: Sistema de Análisis y Visualización de Estadísticas en Tiempo Real para Counter-Strike 2
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# Navigation
nav_links:
  - title: Home
    url: /
  - title: Quick Start
    url: /quick-start.html
  - title: API
    url: /api.html
  - title: Config
    url: /config.html
  - title: Deployment
    url: /deployment.html
