name: Build and deploy site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c33e5e44
        with:
          fetch-depth: 0

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@13c3e0490491b10370b2712518ac7aa57b6fe265
